#!/bin/bash
#
# Copyright (c) 2018, Cisco Systems
# All rights reserved. See LICENSE file.
#
set -xe

export AMP_ROOT="$PWD/storage"

# This is expected to fail.
amp bkt_load_fail bucket test-bucket info && exit 1 || exit 0
