#!/bin/bash
#
# Copyright (c) 2018, Cisco Systems
# All rights reserved. See LICENSE file.
#
set -xe

export AMP_ROOT="$PWD/storage"

# This is expected to fail.
amp bkt_audit_fail bucket test-bucket audit && exit 1 || exit 0
